---
- name: 0.系统初始化
  gather_facts: false
  hosts:
    - k8s
    - etcd
  roles:
    - common
  tags: common

- name: 1.自签证书
  gather_facts: false
  hosts: localhost
  roles:
    - tls
  tags:
    - tls

- name: 2.部署docker
  gather_facts: false
  hosts: k8s
  roles:
    - docker
  tags: docker

- name: 3.部署etcd集群
  gather_facts: false
  hosts: etcd
  roles:
    - etcd
  tags: etcd

- name: 4.部署k8s master
  gather_facts: false
  hosts: master
  roles:
    - master
  tags: master

